        <footer>
                <p>Copyright &copy; 2025 Kwnd Creative</p>
                <a href="https://github.com/106489702/Razeem_1430_G06-webpage">GitHub Repository</a>
                <a href="https://razzeenfri1430g06.atlassian.net/jira/software/projects/SCRUM/boards/1?jql=assignee%20IN%20%28712020%3Aefb8f835-5e17-4fd4-8054-2840caf137c2%2C%20712020%3Ab61717f1-9a04-4add-aaa1-8c70e04797a8%29">Jira Board</a>
                <a href="mailto:info@kwndcreate.com">Contact Us</a>
        </footer>
    </body>
</html>